drop TABLE IF EXISTS days;

CREATE TABLE days (
	id          SERIAL PRIMARY KEY,
	travel_id   BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (travel_id) REFERENCES travels(id) ON DELETE CASCADE,

	user_id     VARCHAR(255) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(google_id) ON DELETE CASCADE,

	day_number  INTEGER NOT NULL,
	date        DATE NOT NULL,
	description TEXT,

	created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);