
DROP TABLE IF EXISTS travels;

CREATE TABLE travels (
	id          SERIAL PRIMARY KEY,
	user_id     VARCHAR(255) NOT NULL REFERENCES users(google_id) ON DELETE CASCADE,
	name        VARCHAR(255) NOT NULL,
	start_date  DATE NOT NULL,
	end_date    DATE NOT NULL,

	description TEXT,
	destination VARCHAR(255) NOT NULL,

	created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);