DROP TABLE IF EXISTS itineraries;

CREATE TABLE itineraries (
	id          SERIAL PRIMARY KEY,
	travel_id   INTEGER NOT NULL REFERENCES travels(id) ON DELETE CASCADE,
	user_id     VARCHAR(255) NOT NULL REFERENCES users(google_id) ON DELETE CASCADE,

	name        VARCHAR(255) NOT NULL,
	start_date  DATE NOT NULL,
	end_date    DATE NOT NULL,

	purpose     TEXT,
	destination VARCHAR(255) NOT NULL,

	created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
